// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoList.DAL.Context;

#nullable disable

namespace TodoList.DAL.Migrations
{
    [DbContext(typeof(TodoListDbContext))]
    [Migration("20231108002726_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TodoList.DAL.Entities.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Unde voluptatem repellendus quasi voluptatem atque eos vel dignissimos eveniet.",
                            IsCompleted = false,
                            Title = "Fugiat delectus fugit.",
                            UserId = 4
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Et asperiores odio doloribus est sit numquam minima delectus et.",
                            IsCompleted = false,
                            Title = "Unde aliquid ex sit iusto dignissimos aut qui quod.",
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Iure saepe omnis corporis ex explicabo vero qui occaecati aut.",
                            IsCompleted = false,
                            Title = "Repellat nesciunt voluptatem sunt labore odio et.",
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Incidunt et accusamus tempora fugiat asperiores omnis ea.",
                            IsCompleted = true,
                            Title = "Ipsum beatae quo quos numquam.",
                            UserId = 6
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ex aut dignissimos.",
                            IsCompleted = true,
                            Title = "Et quis labore earum incidunt aspernatur soluta nobis nostrum.",
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sint nam molestiae enim deserunt.",
                            IsCompleted = true,
                            Title = "Ut dolorem vitae odio vitae voluptatem consequatur ut.",
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Velit earum reiciendis doloremque aut et ut.",
                            IsCompleted = false,
                            Title = "Et ratione rerum.",
                            UserId = 6
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Temporibus voluptas voluptatum aut officia quo iusto facere autem.",
                            IsCompleted = false,
                            Title = "Ipsum ipsa magnam non provident earum.",
                            UserId = 6
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Voluptate ad aut.",
                            IsCompleted = false,
                            Title = "Est autem voluptates et quia qui rerum.",
                            UserId = 3
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Eos nemo voluptate mollitia dolorem.",
                            IsCompleted = true,
                            Title = "Sunt dolores aut inventore et quia necessitatibus.",
                            UserId = 3
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Voluptatem dolores architecto nihil facilis quo dignissimos excepturi.",
                            IsCompleted = true,
                            Title = "Molestiae tempora consectetur ex a.",
                            UserId = 4
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sint non animi et culpa repellat distinctio error.",
                            IsCompleted = false,
                            Title = "Delectus fuga itaque accusamus voluptatem harum qui.",
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Aliquid similique velit perferendis vero id id voluptate aut.",
                            IsCompleted = true,
                            Title = "Beatae eaque nam blanditiis incidunt placeat voluptatibus commodi error illo.",
                            UserId = 6
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nam eos consequuntur perspiciatis corporis.",
                            IsCompleted = false,
                            Title = "Dignissimos cumque distinctio quidem dolores nihil maiores enim.",
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cumque culpa doloremque ullam similique qui inventore.",
                            IsCompleted = true,
                            Title = "Suscipit ut culpa.",
                            UserId = 5
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Culpa repellendus quas nobis nihil architecto totam omnis.",
                            IsCompleted = false,
                            Title = "Veniam doloremque ipsam eius possimus similique fugit corrupti.",
                            UserId = 6
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Harum suscipit non.",
                            IsCompleted = true,
                            Title = "Est voluptas totam ratione maxime.",
                            UserId = 7
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Velit eos aut.",
                            IsCompleted = false,
                            Title = "Officia non culpa explicabo incidunt.",
                            UserId = 7
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tempora aspernatur officia dolorum et.",
                            IsCompleted = false,
                            Title = "Autem velit eveniet.",
                            UserId = 5
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Facere consequuntur reiciendis ut totam accusantium possimus enim molestiae porro.",
                            IsCompleted = true,
                            Title = "Natus ipsum voluptatum quidem itaque omnis iste explicabo est rem.",
                            UserId = 7
                        });
                });

            modelBuilder.Entity("TodoList.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Noe60@hotmail.com",
                            PasswordHash = "pl2r67AEAFyf93hI7xpQUfbQiWZT4+SqkB8kpb3ZQ60acBca",
                            Username = "Vanessa_VonRueden"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Tiffany38@gmail.com",
                            PasswordHash = "f/2ghg0oJMcWEBu6kcc6tQXkUjbQeiGgQ54fZteA1x0jpO+i",
                            Username = "Dannie_Zieme"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Amiya62@yahoo.com",
                            PasswordHash = "jczOv5adAUQ9aOP5DSgyK7DDvYoZ8aq0PpkWpEGpaTQoMv2n",
                            Username = "Lisandro12"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Hailee96@hotmail.com",
                            PasswordHash = "yjbIuAEyApdjspeMUj+d7ysnTJj+QNgHwQKORCjSaux+G8bs",
                            Username = "Gussie54"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Gregoria.Kunze89@hotmail.com",
                            PasswordHash = "SlnevLDroH7d5ehue2fCJhPP484Jdrp3eTxWeox2yeMgJ21K",
                            Username = "Guido.Krajcik"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Aliyah14@gmail.com",
                            PasswordHash = "dAK+hXRdevAeNafm9NFs3uWKU6X7WPN3/Qmc0rR2vy+qNXGv",
                            Username = "Ephraim_Emmerich"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Zita_Spinka@gmail.com",
                            PasswordHash = "gmM2F1OHpMZFWg0CvFkrTU79rYZD+tsqeifIIx4s4ed8xKWq",
                            Username = "Deonte.Buckridge86"
                        });
                });

            modelBuilder.Entity("TodoList.DAL.Entities.Task", b =>
                {
                    b.HasOne("TodoList.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
